# Sitewide configuration settings. Set `title` to the site title, which
# will be appended to the URL following {{page.title}} 
title: "Mike Down South"
sub_title: "Wandering around South America"

permalink: /:year/:month/:day/:title/
baseurl: /MikeDownSouth
include: ['_pages']

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page/:num"

destination:  ./_site/MikeDownSouth
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

#GitHub URL for AllYourTexts application
url_GitHub: "https://github.com/TheWaySnrubThinks/MikeDownSouth"
